name: build and test

on: push

jobs:
  build-test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 2

      - name: Build and test
        uses: kxcdev/ocaml-general-gha@v1
